

export const translations = {
  en: {
    // General
    language: "English",
    companyName: "Nuba Flower Tours",
    search: "Search...",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    loading: "Loading...",
    noData: "No data available.",
    view: "View",
    upload: "Upload",
    file: "File",
    removeFile: "Remove File",
    download: "Download",
    filter: "Filter",
    resetFilters: "Reset",
    all: "All",
    startDate: "Start Date",
    endDate: "End Date",
    priority: "Priority",
    dueDate: "Due Date",
    dateAddedRange: "Date Added Range",
    bookingDateRange: "Booking Date Range",
    age: "Age",
    gender: "Gender",
    Male: "Male",
    Female: "Female",
    guests: "Guests in Room",
    preview: "Preview Report",
    downloadReport: "Download",
    page: "Page",
    of: "of",
    noPreview: "No preview available for this report type.",
    previewFor: "Preview for",
    reportDate: "Report Date",

    // Auth & Users
    login: "Login",
    username: "Username",
    password: "Password",
    logout: "Logout",
    loginWelcome: "Welcome Back!",
    loginSub: "Please sign in to your account.",
    loginError: "Invalid username or password.",
    Admin: "Admin",
    Manager: "Manager",
    Staff: "Staff",
    users: "Users",
    addUser: "Add New User",
    editUser: "Edit User",
    name: "Name",
    role: "Role",
    newPasswordOptional: "New Password (optional)",
    confirmPassword: "Confirm Password",
    userSavedSuccess: "User saved successfully.",
    userDeletedSuccess: "User has been deleted.",
    noUsersFound: "No users found.",
    noUsersFoundSub: "Add your first user to get started.",
    confirmDeleteUserMessage: "Are you sure you want to delete this user?",
    usernameExistsError: "This username already exists.",
    passwordsDoNotMatchError: "Passwords do not match.",
    passwordRequiredError: "Password is required for new users.",
    cannotDeleteSelfError: "You cannot delete your own account.",
    profile: "Profile",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    passwordChangedSuccess: "Your password has been changed successfully.",
    currentPasswordIncorrect: "The current password you entered is incorrect.",

    // Sidebar
    dashboard: "Dashboard",
    customers: "Customers",
    packages: "Packages",
    bookings: "Bookings",
    finance: "Finance",
    reports: "Reports",
    tasks: "Tasks",
    activityLog: "Activity Log",

    // Dashboard
    welcomeMessage: "Welcome Back, {name}!",
    welcomeSub: "Here's a snapshot of your agency's performance.",
    totalCustomers: "Total Customers",
    activeBookings: "Active Bookings",
    totalRevenue: "Total Revenue",
    totalExpenses: "Total Expenses",
    financialPerformance: "Financial Performance",
    income: "Revenue",
    expenses: "Expenses",
    packagePopularity: "Package Popularity",
    recentActivity: "Recent Activity",
    viewAll: "View All",
    bookingId: "Booking ID",
    customer: "Customer",
    package: "Package",
    status: "Status",
    
    // Customers
    addCustomer: "Add New Customer",
    editCustomer: "Edit Customer",
    customerDetails: "Customer Details",
    customerName: "Customer Name",
    phone: "Phone Number",
    email: "Email",
    passportNumber: "Passport Number",
    passportExpiry: "Passport Expiry",
    documents: "Documents",
    uploadDocument: "Upload Document",
    documentName: "Document Name",
    documentType: "Document Type",
    manageDocuments: "Manage Documents",
    noDocuments: "No documents uploaded for this customer yet.",
    confirmDeleteDocument: "Are you sure you want to delete this document?",
    uploadAndScan: "Upload & Scan Passport",
    scanInstructions: "Click to upload an image or PDF",
    scanning: "Scanning...",
    scanError: "Scan failed. Please use a clear image or enter details manually.",
    scanSuccess: "Scan Successful!",
    scanSuccessFields: "Fields auto-filled. Please review.",
    orEnterManually: "Or enter details manually",
    searchCustomers: "Search by name, phone, passport...",
    noCustomersFound: "No customers found.",
    noCustomersFoundSub: "Try adjusting your search or filters.",
    addNewCustomerCTA: "Add New Customer",
    selectOrDrop: "Select or drop files here",
    uploadingFiles: "Uploading Files",
    uploading: "Uploading...",
    savedDocuments: "Saved Documents",


    // Packages
    addPackage: "Add New Package",
    editPackage: "Edit Package",
    packageCode: "Package Code",
    packageName: "Package Name",
    packageType: "Type",
    duration: "Duration (days)",
    price: "Price (EGP)",
    description: "Description",
    hotelDetails: "Hotel Details",
    hotelMakkah: "Makkah Hotel",
    hotelMadinah: "Madinah Hotel",
    includes: "Includes",
    includesHint: "e.g., Flights, Visa, Breakfast",
    isFeatured: "Featured Package",
    searchPackages: "Search by name or code...",
    noPackagesFound: "No packages found.",
    noPackagesFoundSub: "Would you like to create a new one?",
    addNewPackageCTA: "Add New Package",
    bookNow: "Book Now",
    
    // Bookings
    addBooking: "Add New Booking",
    editBooking: "Edit Booking",
    bookingDetails: "Booking Details",
    customerInformation: "Customer Information",
    packageInformation: "Package Information",
    ticketInformation: "Ticket Information",
    flightInformation: "Flight Information",
    roomAndMealInformation: "Room & Meal Information",
    bookingDate: "Booking Date",
    totalPaid: "Total Paid",
    selectBooking: "Select a booking",
    selectBookingType: "Select Booking Type",
    packageBooking: "Package Booking",
    packageBookingDescription: "Book a complete Hajj or Umrah package for a customer.",
    ticketOnlyBookingDescription: "Sell only flight tickets without a package.",
    addFlightDetails: "Add Flight Details",
    removeFlightDetails: "Remove Flight Details",
    sellTicketOnly: "Sell Flight Ticket Only",
    ticketCostPrice: "Ticket Cost Price",
    ticketTotalPaid: "Ticket Total Paid (Sale Price)",
    ticketOnlySale: "Ticket Only Sale",
    flightDetailsRequiredForTicketed: "Flight details are required when booking status is 'Ticketed'.",
    airline: "Airline",
    flightNumber: "Flight Number",
    departureDate: "Departure Date",
    returnDate: "Return Date",
    roomType: "Room Type",
    meals: "Meals",
    exportExcel: "Export Excel",
    exportPDF: "Export PDF",
    noDataToExport: "There is no data to export.",
    withoutBed: "Without Bed (Infant/Child)",
    withoutBedShort: "Without Bed",
    noPaymentsMade: "No payments have been recorded yet.",
    // Meal Types
    OnlyBed: "Only Bed",
    Breakfast: "Breakfast",
    HalfBoard: "Half Board",
    FullBoard: "Full Board",
    searchBookings: "Search by customer name or ID...",
    noBookingsFound: "No bookings found.",
    noBookingsFoundSub: "Try adjusting your filters or create a new booking.",
    addNewBookingCTA: "Add New Booking",
    // Booking Statuses
    Pending: "Pending",
    Deposited: "Deposited",
    Confirmed: "Confirmed",
    VisaProcessed: "Visa Processed",
    Ticketed: "Ticketed",
    Departed: "Departed",
    Completed: "Completed",
    Cancelled: "Cancelled",
    
    // Finance
    financialOverview: "Financial Overview",
    profit: "Profit",
    ticketProfit: "Ticket Profit",
    recentPayments: "Recent Revenue",
    recentExpenses: "Recent Expenses",
    addPayment: "Add Amount",
    addExpense: "Add Expense",
    amount: "Amount",
    category: "Category",
    paymentDate: "Payment Date",
    paymentMethod: "Payment Method",
    vatAmount: "VAT Amount",
    paidTo: "Paid To",
    financials: "Financials",
    paid: "Paid",
    // Payment Methods
    Cash: "Cash",
    BankTransfer: "Bank Transfer",
    CreditCard: "Credit Card",
    expenseCategories: "Expense Categories",
    addCategory: "Add New Category",
    editCategory: "Edit Category",
    categoryName: "Category Name",
    noCategoriesFound: "No categories found.",
    noCategoriesFoundSub: "Add your first expense category to get started.",
    confirmDeleteCategoryMessage: "Are you sure you want to delete this category? This will not affect existing expenses.",
    
    // Reports
    generateReports: "Generate Reports",
    reportType: "Report Type",
    customerList: "Customer List",
    bookingList: "Booking List",
    financialSummary: "Financial Summary",
    hotelRoomingList: "Hotel Rooming List",
    generatePDF: "Generate PDF",
    generateExcel: "Generate Excel",
    reportLayout: "Report Layout",
    standardList: "Standard List",
    roomLayout: "Room Layout",
    hotelRoomingListQuint: "Quintuple",
    
    // Tasks
    addTask: "Add New Task",
    editTask: "Edit Task",
    taskTitle: "Task Title",
    relatedBooking: "Related Booking (Optional)",
    noRelatedBooking: "No related booking",
    markAsComplete: "Mark as complete",
    markAsIncomplete: "Mark as incomplete",
    overdue: "Overdue",
    noTasksFound: "No tasks found.",
    noTasksFoundSub: "Try adjusting your filters or create a new task.",
    Incomplete: "Incomplete",
    // Task Priorities
    High: "High",
    Medium: "Medium",
    Low: "Low",

    // Activity Log
    user: "User",
    action: "Action",
    entity: "Entity",
    details: "Details",
    timestamp: "Timestamp",
    searchActivity: "Search by details or user...",
    noActivityFound: "No activity found.",
    noActivityFoundSub: "No actions have been recorded yet.",
    actionType: "Action Type",
    Created: "Created",
    Updated: "Updated",
    Deleted: "Deleted",
    // Log Messages
    logCreatedCustomer: "Created Customer: {details}",
    logUpdatedCustomer: "Updated Customer: {details}",
    logDeletedCustomer: "Deleted Customer: {details}",
    logCreatedPackage: "Created Package: {details}",
    logUpdatedPackage: "Updated Package: {details}",
    logDeletedPackage: "Deleted Package: {details}",
    logCreatedBooking: "Created Booking: {details}",
    logUpdatedBooking: "Updated Booking: {details}",
    logDeletedBooking: "Deleted Booking: {details}",
    logCreatedPayment: "Added Payment of {amount} to {details}",
    logCreatedExpense: "Added Expense of {amount} for {details}",
    logCreatedTask: "Created Task: {details}",
    logUpdatedTask: "Updated Task: {details}",
    logDeletedTask: "Deleted Task: {details}",
    logCompletedTask: "Completed Task: {details}",
    logIncompleteTask: "Marked Task as Incomplete: {details}",
    logCreatedUser: "Created User: {details}",
    logUpdatedUser: "Updated User: {details}",
    logDeletedUser: "Deleted User: {details}",
    logCreatedDocument: "Added Document '{docName}' to {details}",
    logDeletedDocument: "Deleted Document '{docName}' from {details}",
    logCreatedExpenseCategory: "Created Expense Category: {details}",
    logUpdatedExpenseCategory: "Updated Expense Category: {details}",
    logDeletedExpenseCategory: "Deleted Expense Category: {details}",


    // Invoice & Receipt
    invoice: "Invoice",
    flightTicketInvoice: "Flight Ticket Invoice",
    invoiceDate: "Invoice Date",
    billTo: "Bill To",
    itemDescription: "Item Description",
    // FIX: Renamed from 'details' to avoid duplicate key error.
    invoiceDetails: "Details",
    subtotal: "Subtotal",
    amountPaid: "Amount Paid",
    amountDue: "Amount Due",
    paymentHistory: "Payment History",
    receipt: "Receipt",
    paymentDetails: "Payment Details",
    bookingSummary: "Booking Summary",
    totalPackagePrice: "Total Package Price",
    totalAmount: "Total Amount",
    totalPaidToDate: "Total Paid to Date",
    remainingBalance: "Remaining Balance",
    price_unit: "EGP {price}",
    days_unit: "days",
    
    // Confirmations
    confirmDeletionTitle: "Confirm Deletion",
    confirmDeletionMessage: "This action cannot be undone. Are you sure you want to proceed?",
    confirmInvoiceGeneration: "Are you sure you want to generate this invoice?",
    confirmReceiptGeneration: "Are you sure you want to generate this receipt?",
    confirmDeleteCustomer: "Are you sure you want to delete this customer? This action cannot be undone.",
    confirmDeletePackage: "Are you sure you want to delete this package? This action cannot be undone.",
    confirmDeleteBooking: "Are you sure you want to delete this booking? This action cannot be undone.",

    // Toasts
    success: "Success",
    error: "Error",
    info: "Info",
    invoiceGeneratedSuccess: "Invoice has been generated and downloaded.",
    receiptGeneratedSuccess: "Receipt has been generated and downloaded.",
    bookingSavedSuccess: "Booking saved successfully.",
    bookingDeletedSuccess: "Booking has been deleted.",
    bookingStatusUpdated: "Booking {bookingId} status automatically updated to Confirmed.",
    customerSavedSuccess: "Customer details saved successfully.",
    customerDeletedSuccess: "Customer has been deleted.",
    documentAddedSuccess: "Document uploaded successfully.",
    documentDeletedSuccess: "Document has been deleted.",
    packageSavedSuccess: "Package saved successfully.",
    packageDeletedSuccess: "Package has been deleted.",
    paymentAddedSuccess: "Payment added successfully.",
    expenseAddedSuccess: "Expense added successfully.",
    taskSavedSuccess: "Task saved successfully.",
    taskDeletedSuccess: "Task has been deleted.",
    taskStatusChanged: "Task status updated.",
    categorySavedSuccess: "Category saved successfully.",
    categoryDeletedSuccess: "Category has been deleted.",
    fillRequiredFieldsWarning: "Please fill all required fields.",
    genericError: "An unexpected error occurred. Please try again.",
    passportExpiryWarning: "Passport must be valid for at least 6 months after the departure date.",
    passportSoonToExpireWarning: "Passport must be valid for at least 6 months from today.",
    apiKeyNotConfiguredError: "Scanning service is not configured. Please contact support.",
    flightDetailsMissingForInvoice: "Cannot generate invoice: flight details are missing for this ticket sale.",
    invoicePackageMissingError: "Cannot generate invoice: The package for this booking could not be found (it may have been deleted).",
    invoiceCustomerMissingError: "Cannot generate invoice: The customer for this booking could not be found (they may have been deleted).",
  }
};