

export const translations = {
  en: {
    // General
    companyName: "Nuba Flower Tours",
    search: "Search...",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    loading: "Loading...",
    noData: "No data available.",
    view: "View",
    upload: "Upload",
    file: "File",
    removeFile: "Remove File",
    download: "Download",
    filter: "Filter",
    resetFilters: "Reset",
    all: "All",
    startDate: "Start Date",
    endDate: "End Date",
    priority: "Priority",
    dueDate: "Due Date",
    dateAddedRange: "Date Added Range",
    bookingDateRange: "Booking Date Range",
    age: "Age",
    gender: "Gender",
    Male: "Male",
    Female: "Female",
    guests: "Guests in Room",
    preview: "Preview Report",
    downloadReport: "Download",
    page: "Page",
    of: "of",
    noPreview: "No preview available for this report type.",
    previewFor: "Preview for",

    // Auth & Users
    login: "Login",
    username: "Username",
    password: "Password",
    logout: "Logout",
    loginWelcome: "Welcome Back!",
    loginSub: "Please sign in to your account.",
    loginError: "Invalid username or password.",
    Admin: "Admin",
    Manager: "Manager",
    Staff: "Staff",
    users: "Users",
    addUser: "Add New User",
    editUser: "Edit User",
    name: "Name",
    role: "Role",
    newPasswordOptional: "New Password (optional)",
    confirmPassword: "Confirm Password",
    userSavedSuccess: "User saved successfully.",
    userDeletedSuccess: "User has been deleted.",
    noUsersFound: "No users found.",
    noUsersFoundSub: "Add your first user to get started.",
    confirmDeleteUserMessage: "Are you sure you want to delete this user?",
    usernameExistsError: "This username already exists.",
    passwordsDoNotMatchError: "Passwords do not match.",
    passwordRequiredError: "Password is required for new users.",
    cannotDeleteSelfError: "You cannot delete your own account.",
    profile: "Profile",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmNewPassword: "Confirm New Password",
    passwordChangedSuccess: "Your password has been changed successfully.",
    currentPasswordIncorrect: "The current password you entered is incorrect.",

    // Sidebar
    dashboard: "Dashboard",
    customers: "Customers",
    packages: "Packages",
    bookings: "Bookings",
    finance: "Finance",
    reports: "Reports",
    tasks: "Tasks",
    activityLog: "Activity Log",

    // Dashboard
    welcomeMessage: "Welcome Back, {name}!",
    welcomeSub: "Here's a snapshot of your agency's performance.",
    totalCustomers: "Total Customers",
    activeBookings: "Active Bookings",
    totalRevenue: "Total Revenue",
    totalExpenses: "Total Expenses",
    financialPerformance: "Financial Performance",
    income: "Revenue",
    expenses: "Expenses",
    packagePopularity: "Package Popularity",
    recentActivity: "Recent Activity",
    viewAll: "View All",
    bookingId: "Booking ID",
    customer: "Customer",
    package: "Package",
    status: "Status",
    
    // Customers
    addCustomer: "Add New Customer",
    editCustomer: "Edit Customer",
    customerDetails: "Customer Details",
    customerName: "Customer Name",
    phone: "Phone Number",
    email: "Email",
    passportNumber: "Passport Number",
    passportExpiry: "Passport Expiry",
    documents: "Documents",
    uploadDocument: "Upload Document",
    documentName: "Document Name",
    documentType: "Document Type",
    manageDocuments: "Manage Documents",
    noDocuments: "No documents uploaded for this customer yet.",
    confirmDeleteDocument: "Are you sure you want to delete this document?",
    uploadAndScan: "Upload & Scan Passport",
    scanInstructions: "Click to upload an image or PDF",
    scanning: "Scanning...",
    scanError: "Scan failed. Please use a clear image or enter details manually.",
    scanSuccess: "Scan Successful!",
    scanSuccessFields: "Fields auto-filled. Please review.",
    orEnterManually: "Or enter details manually",
    searchCustomers: "Search by name, phone, passport...",
    noCustomersFound: "No customers found.",
    noCustomersFoundSub: "Try adjusting your search or filters.",
    addNewCustomerCTA: "Add New Customer",
    selectOrDrop: "Select or drop files here",
    uploadingFiles: "Uploading Files",
    uploading: "Uploading...",
    savedDocuments: "Saved Documents",


    // Packages
    addPackage: "Add New Package",
    editPackage: "Edit Package",
    packageCode: "Package Code",
    packageName: "Package Name",
    packageType: "Type",
    duration: "Duration (days)",
    price: "Price (EGP)",
    description: "Description",
    hotelDetails: "Hotel Details",
    hotelMakkah: "Makkah Hotel",
    hotelMadinah: "Madinah Hotel",
    includes: "Includes",
    includesHint: "e.g., Flights, Visa, Breakfast",
    isFeatured: "Featured Package",
    searchPackages: "Search by name or code...",
    noPackagesFound: "No packages found.",
    noPackagesFoundSub: "Would you like to create a new one?",
    addNewPackageCTA: "Add New Package",
    
    // Bookings
    addBooking: "Add New Booking",
    editBooking: "Edit Booking",
    bookingDate: "Booking Date",
    totalPaid: "Total Paid",
    selectBooking: "Select a booking",
    selectBookingType: "Select Booking Type",
    packageBooking: "Package Booking",
    packageBookingDescription: "Book a complete Hajj or Umrah package for a customer.",
    ticketOnlyBookingDescription: "Sell only flight tickets without a package.",
    addFlightDetails: "Add Flight Details",
    removeFlightDetails: "Remove Flight Details",
    sellTicketOnly: "Sell Flight Ticket Only",
    ticketCostPrice: "Ticket Cost Price",
    ticketTotalPaid: "Ticket Total Paid (Sale Price)",
    ticketOnlySale: "Ticket Only Sale",
    flightDetailsRequiredForTicketed: "Flight details are required when booking status is 'Ticketed'.",
    airline: "Airline",
    flightNumber: "Flight Number",
    departureDate: "Departure Date",
    returnDate: "Return Date",
    roomType: "Room Type",
    meals: "Meals",
    exportExcel: "Export Excel",
    noDataToExport: "There is no data to export.",
    withoutBed: "Without Bed (Infant/Child)",
    withoutBedShort: "Without Bed",
    // Meal Types
    OnlyBed: "Only Bed",
    Breakfast: "Breakfast",
    HalfBoard: "Half Board",
    FullBoard: "Full Board",
    searchBookings: "Search by customer name or ID...",
    noBookingsFound: "No bookings found.",
    noBookingsFoundSub: "Try adjusting your filters or create a new booking.",
    addNewBookingCTA: "Add New Booking",
    // Booking Statuses
    Pending: "Pending",
    Deposited: "Deposited",
    Confirmed: "Confirmed",
    VisaProcessed: "Visa Processed",
    Ticketed: "Ticketed",
    Departed: "Departed",
    Completed: "Completed",
    Cancelled: "Cancelled",
    
    // Finance
    financialOverview: "Financial Overview",
    profit: "Profit",
    ticketProfit: "Ticket Profit",
    recentPayments: "Recent Revenue",
    recentExpenses: "Recent Expenses",
    addPayment: "Add Amount",
    addExpense: "Add Expense",
    amount: "Amount",
    category: "Category",
    paymentDate: "Payment Date",
    paymentMethod: "Payment Method",
    vatAmount: "VAT Amount",
    paidTo: "Paid To",
    // Payment Methods
    Cash: "Cash",
    BankTransfer: "Bank Transfer",
    CreditCard: "Credit Card",
    expenseCategories: "Expense Categories",
    addCategory: "Add New Category",
    editCategory: "Edit Category",
    categoryName: "Category Name",
    noCategoriesFound: "No categories found.",
    noCategoriesFoundSub: "Add your first expense category to get started.",
    confirmDeleteCategoryMessage: "Are you sure you want to delete this category? This will not affect existing expenses.",
    
    // Reports
    generateReports: "Generate Reports",
    reportType: "Report Type",
    customerList: "Customer List",
    bookingList: "Booking List",
    financialSummary: "Financial Summary",
    hotelRoomingList: "Hotel Rooming List",
    generatePDF: "Generate PDF",
    generateExcel: "Generate Excel",
    reportLayout: "Report Layout",
    standardList: "Standard List",
    roomLayout: "Room Layout",
    hotelRoomingListQuint: "Quintuple",
    
    // Tasks
    addTask: "Add New Task",
    editTask: "Edit Task",
    taskTitle: "Task Title",
    relatedBooking: "Related Booking (Optional)",
    noRelatedBooking: "No related booking",
    markAsComplete: "Mark as complete",
    markAsIncomplete: "Mark as incomplete",
    overdue: "Overdue",
    noTasksFound: "No tasks found.",
    noTasksFoundSub: "Try adjusting your filters or create a new task.",
    Incomplete: "Incomplete",
    // Task Priorities
    High: "High",
    Medium: "Medium",
    Low: "Low",

    // Activity Log
    user: "User",
    action: "Action",
    entity: "Entity",
    details: "Details",
    timestamp: "Timestamp",
    searchActivity: "Search by details or user...",
    noActivityFound: "No activity found.",
    noActivityFoundSub: "No actions have been recorded yet.",
    actionType: "Action Type",
    Created: "Created",
    Updated: "Updated",
    Deleted: "Deleted",
    // Log Messages
    logCreatedCustomer: "Created Customer: {details}",
    logUpdatedCustomer: "Updated Customer: {details}",
    logDeletedCustomer: "Deleted Customer: {details}",
    logCreatedPackage: "Created Package: {details}",
    logUpdatedPackage: "Updated Package: {details}",
    logDeletedPackage: "Deleted Package: {details}",
    logCreatedBooking: "Created Booking: {details}",
    logUpdatedBooking: "Updated Booking: {details}",
    logDeletedBooking: "Deleted Booking: {details}",
    logCreatedPayment: "Added Payment of {amount} to {details}",
    logCreatedExpense: "Added Expense of {amount} for {details}",
    logCreatedTask: "Created Task: {details}",
    logUpdatedTask: "Updated Task: {details}",
    logDeletedTask: "Deleted Task: {details}",
    logCompletedTask: "Completed Task: {details}",
    logIncompleteTask: "Marked Task as Incomplete: {details}",
    logCreatedUser: "Created User: {details}",
    logUpdatedUser: "Updated User: {details}",
    logDeletedUser: "Deleted User: {details}",
    logCreatedDocument: "Added Document '{docName}' to {details}",
    logDeletedDocument: "Deleted Document '{docName}' from {details}",
    logCreatedExpenseCategory: "Created Expense Category: {details}",
    logUpdatedExpenseCategory: "Updated Expense Category: {details}",
    logDeletedExpenseCategory: "Deleted Expense Category: {details}",


    // Invoice & Receipt
    invoice: "Invoice",
    flightTicketInvoice: "Flight Ticket Invoice",
    invoiceDate: "Invoice Date",
    billTo: "Bill To",
    itemDescription: "Item Description",
    subtotal: "Subtotal",
    amountPaid: "Amount Paid",
    amountDue: "Amount Due",
    paymentHistory: "Payment History",
    receipt: "Receipt",
    paymentDetails: "Payment Details",
    bookingSummary: "Booking Summary",
    totalPackagePrice: "Total Package Price",
    totalPaidToDate: "Total Paid to Date",
    remainingBalance: "Remaining Balance",
    
    // Confirmations
    confirmDeletionTitle: "Confirm Deletion",
    confirmDeletionMessage: "This action cannot be undone. Are you sure you want to proceed?",
    confirmInvoiceGeneration: "Are you sure you want to generate this invoice?",
    confirmReceiptGeneration: "Are you sure you want to generate this receipt?",
    confirmDeleteCustomer: "Are you sure you want to delete this customer? This action cannot be undone.",
    confirmDeletePackage: "Are you sure you want to delete this package? This action cannot be undone.",
    confirmDeleteBooking: "Are you sure you want to delete this booking? This action cannot be undone.",

    // Toasts
    success: "Success",
    error: "Error",
    invoiceGeneratedSuccess: "Invoice has been generated and downloaded.",
    receiptGeneratedSuccess: "Receipt generated successfully.",
    bookingSavedSuccess: "Booking saved successfully.",
    bookingDeletedSuccess: "Booking has been deleted.",
    customerSavedSuccess: "Customer details saved successfully.",
    customerDeletedSuccess: "Customer has been deleted.",
    documentAddedSuccess: "Document uploaded successfully.",
    documentDeletedSuccess: "Document has been deleted.",
    packageSavedSuccess: "Package saved successfully.",
    packageDeletedSuccess: "Package has been deleted.",
    paymentAddedSuccess: "Payment added successfully.",
    expenseAddedSuccess: "Expense added successfully.",
    taskSavedSuccess: "Task saved successfully.",
    taskDeletedSuccess: "Task has been deleted.",
    taskStatusChanged: "Task status updated.",
    categorySavedSuccess: "Category saved successfully.",
    categoryDeletedSuccess: "Category has been deleted.",
    fillRequiredFieldsWarning: "Please fill all required fields.",
    genericError: "An unexpected error occurred. Please try again.",
    passportExpiryWarning: "Passport must be valid for at least 6 months after the departure date.",
    passportSoonToExpireWarning: "Passport must be valid for at least 6 months from today.",
    apiKeyNotConfiguredError: "Scanning service is not configured. Please contact support.",
    flightDetailsMissingForInvoice: "Cannot generate invoice: flight details are missing for this ticket sale.",
    invoicePackageMissingError: "Cannot generate invoice: The package for this booking could not be found (it may have been deleted).",
    invoiceCustomerMissingError: "Cannot generate invoice: The customer for this booking could not be found (they may have been deleted).",
  },
  ar: {
    // General
    companyName: "زهرة النوبة للسياحة",
    search: "بحث...",
    actions: "إجراءات",
    edit: "تعديل",
    delete: "حذف",
    add: "إضافة",
    save: "حفظ",
    cancel: "إلغاء",
    close: "إغلاق",
    loading: "جاري التحميل...",
    noData: "لا توجد بيانات متاحة.",
    view: "عرض",
    upload: "رفع",
    file: "ملف",
    removeFile: "إزالة الملف",
    download: "تنزيل",
    filter: "تصفية",
    resetFilters: "إعادة تعيين",
    all: "الكل",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    priority: "الأولوية",
    dueDate: "تاريخ الاستحقاق",
    dateAddedRange: "نطاق تاريخ الإضافة",
    bookingDateRange: "نطاق تاريخ الحجز",
    age: "العمر",
    gender: "الجنس",
    Male: "ذكر",
    Female: "أنثى",
    guests: "النزلاء في الغرفة",
    preview: "معاينة التقرير",
    downloadReport: "تنزيل",
    page: "صفحة",
    of: "من",
    noPreview: "لا توجد معاينة متاحة لهذا النوع من التقارير.",
    previewFor: "معاينة لـ",

    // Auth & Users
    login: "تسجيل الدخول",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    logout: "تسجيل الخروج",
    loginWelcome: "أهلاً بعودتك!",
    loginSub: "الرجاء تسجيل الدخول إلى حسابك.",
    loginError: "اسم المستخدم أو كلمة المرور غير صحيحة.",
    Admin: "مسؤول",
    Manager: "مدير",
    Staff: "موظف",
    users: "المستخدمون",
    addUser: "إضافة مستخدم جديد",
    editUser: "تعديل المستخدم",
    name: "الاسم",
    role: "الدور",
    newPasswordOptional: "كلمة مرور جديدة (اختياري)",
    confirmPassword: "تأكيد كلمة المرور",
    userSavedSuccess: "تم حفظ المستخدم بنجاح.",
    userDeletedSuccess: "تم حذف المستخدم.",
    noUsersFound: "لم يتم العثور على مستخدمين.",
    noUsersFoundSub: "أضف المستخدم الأول للبدء.",
    confirmDeleteUserMessage: "هل أنت متأكد من رغبتك في حذف هذا المستخدم؟",
    usernameExistsError: "اسم المستخدم هذا موجود بالفعل.",
    passwordsDoNotMatchError: "كلمتا المرور غير متطابقتين.",
    passwordRequiredError: "كلمة المرور مطلوبة للمستخدمين الجدد.",
    cannotDeleteSelfError: "لا يمكنك حذف حسابك الخاص.",
    profile: "الملف الشخصي",
    changePassword: "تغيير كلمة المرور",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmNewPassword: "تأكيد كلمة المرور الجديدة",
    passwordChangedSuccess: "تم تغيير كلمة المرور بنجاح.",
    currentPasswordIncorrect: "كلمة المرور الحالية التي أدخلتها غير صحيحة.",

    // Sidebar
    dashboard: "لوحة التحكم",
    customers: "العملاء",
    packages: "الباقات",
    bookings: "الحجوزات",
    finance: "المالية",
    reports: "التقارير",
    tasks: "المهام",
    activityLog: "سجل النشاط",

    // Dashboard
    welcomeMessage: "أهلاً بعودتك، {name}!",
    welcomeSub: "إليك لمحة سريعة عن أداء وكالتك.",
    totalCustomers: "إجمالي العملاء",
    activeBookings: "الحجوزات النشطة",
    totalRevenue: "إجمالي الإيرادات",
    totalExpenses: "إجمالي المصروفات",
    financialPerformance: "الأداء المالي",
    income: "الإيرادات",
    expenses: "المصروفات",
    packagePopularity: "شعبية الباقات",
    recentActivity: "النشاط الأخير",
    viewAll: "عرض الكل",
    bookingId: "رقم الحجز",
    customer: "العميل",
    package: "الباقة",
    status: "الحالة",
    
    // Customers
    addCustomer: "إضافة عميل جديد",
    editCustomer: "تعديل بيانات العميل",
    customerDetails: "تفاصيل العميل",
    customerName: "اسم العميل",
    phone: "رقم الهاتف",
    email: "البريد الإلكتروني",
    passportNumber: "رقم جواز السفر",
    passportExpiry: "تاريخ انتهاء جواز السفر",
    documents: "المستندات",
    uploadDocument: "رفع مستند",
    documentName: "اسم المستند",
    documentType: "نوع المستند",
    manageDocuments: "إدارة المستندات",
    noDocuments: "لا توجد مستندات مرفوعة لهذا العميل بعد.",
    confirmDeleteDocument: "هل أنت متأكد من رغبتك في حذف هذا المستند؟",
    uploadAndScan: "رفع ومسح جواز السفر",
    scanInstructions: "انقر لرفع صورة أو ملف PDF",
    scanning: "جاري المسح...",
    scanError: "فشل المسح. يرجى استخدام صورة واضحة أو إدخال التفاصيل يدويًا.",
    scanSuccess: "نجح المسح!",
    scanSuccessFields: "تم ملء الحقول تلقائيًا. يرجى المراجعة.",
    orEnterManually: "أو أدخل التفاصيل يدويًا",
    searchCustomers: "ابحث بالاسم، الهاتف، جواز السفر...",
    noCustomersFound: "لم يتم العثور على عملاء.",
    noCustomersFoundSub: "حاول تعديل بحثك أو الفلاتر.",
    addNewCustomerCTA: "إضافة عميل جديد",
    selectOrDrop: "اختر أو أسقط الملفات هنا",
    uploadingFiles: "ملفات قيد الرفع",
    uploading: "جاري الرفع...",
    savedDocuments: "المستندات المحفوظة",

    // Packages
    addPackage: "إضافة باقة جديدة",
    editPackage: "تعديل الباقة",
    packageCode: "كود الباقة",
    packageName: "اسم الباقة",
    packageType: "النوع",
    duration: "المدة (أيام)",
    price: "السعر (جنيه مصري)",
    description: "الوصف",
    hotelDetails: "تفاصيل الفندق",
    hotelMakkah: "فندق مكة",
    hotelMadinah: "فندق المدينة",
    includes: "تشمل",
    includesHint: "مثال: طيران، تأشيرة، إفطار",
    isFeatured: "باقة مميزة",
    searchPackages: "ابحث بالاسم أو الكود...",
    noPackagesFound: "لم يتم العثور على باقات.",
    noPackagesFoundSub: "هل ترغب في إنشاء باقة جديدة؟",
    addNewPackageCTA: "إضافة باقة جديدة",
    
    // Bookings
    addBooking: "إضافة حجز جديد",
    editBooking: "تعديل الحجز",
    bookingDate: "تاريخ الحجز",
    totalPaid: "المبلغ المدفوع",
    selectBooking: "اختر حجزًا",
    selectBookingType: "اختر نوع الحجز",
    packageBooking: "حجز باقة",
    packageBookingDescription: "حجز باقة حج أو عمرة كاملة لعميل.",
    ticketOnlyBookingDescription: "بيع تذاكر طيران فقط بدون باقة.",
    addFlightDetails: "إضافة تفاصيل الرحلة",
    removeFlightDetails: "إزالة تفاصيل الرحلة",
    sellTicketOnly: "بيع تذكرة طيران فقط",
    ticketCostPrice: "سعر تكلفة التذكرة",
    ticketTotalPaid: "المبلغ الإجمالي المدفوع (سعر البيع)",
    ticketOnlySale: "بيع تذكرة فقط",
    flightDetailsRequiredForTicketed: "تفاصيل الرحلة مطلوبة عندما تكون حالة الحجز 'تم حجز التذكرة'.",
    airline: "شركة الطيران",
    flightNumber: "رقم الرحلة",
    departureDate: "تاريخ المغادرة",
    returnDate: "تاريخ العودة",
    roomType: "نوع الغرفة",
    meals: "الوجبات",
    exportExcel: "تصدير Excel",
    noDataToExport: "لا توجد بيانات للتصدير.",
    withoutBed: "بدون سرير (رضيع/طفل)",
    withoutBedShort: "بدون سرير",
    // Meal Types
    OnlyBed: "سرير فقط",
    Breakfast: "إفطار",
    HalfBoard: "نصف إقامة",
    FullBoard: "إقامة كاملة",
    searchBookings: "ابحث باسم العميل أو رقم الحجز...",
    noBookingsFound: "لم يتم العثور على حجوزات.",
    noBookingsFoundSub: "حاول تعديل الفلاتر أو قم بإنشاء حجز جديد.",
    addNewBookingCTA: "إضافة حجز جديد",
    // Booking Statuses
    Pending: "قيد الانتظار",
    Deposited: "تم دفع العربون",
    Confirmed: "مؤكد",
    VisaProcessed: "تمت معالجة التأشيرة",
    Ticketed: "تم حجز التذكرة",
    Departed: "غادر",
    Completed: "مكتمل",
    Cancelled: "ملغى",

    // Finance
    financialOverview: "نظرة عامة مالية",
    profit: "الربح",
    ticketProfit: "ربح التذاكر",
    recentPayments: "الإيرادات الأخيرة",
    recentExpenses: "المصروفات الأخيرة",
    addPayment: "إضافة مبلغ",
    addExpense: "إضافة مصروف",
    amount: "المبلغ",
    category: "الفئة",
    paymentDate: "تاريخ الدفع",
    paymentMethod: "طريقة الدفع",
    vatAmount: "مبلغ ضريبة القيمة المضافة",
    paidTo: "مدفوع إلى",
    // Payment Methods
    Cash: "نقداً",
    BankTransfer: "تحويل بنكي",
    CreditCard: "بطاقة ائتمان",
    expenseCategories: "فئات المصروفات",
    addCategory: "إضافة فئة جديدة",
    editCategory: "تعديل الفئة",
    categoryName: "اسم الفئة",
    noCategoriesFound: "لم يتم العثور على فئات.",
    noCategoriesFoundSub: "أضف فئة المصروفات الأولى للبدء.",
    confirmDeleteCategoryMessage: "هل أنت متأكد من رغبتك في حذف هذه الفئة؟ لن يؤثر هذا على المصروفات الحالية.",
    
    // Reports
    generateReports: "إنشاء تقارير",
    reportType: "نوع التقرير",
    customerList: "قائمة العملاء",
    bookingList: "قائمة الحجوزات",
    financialSummary: "ملخص مالي",
    hotelRoomingList: "قائمة تسكين الفنادق",
    generatePDF: "إنشاء PDF",
    generateExcel: "إنشاء Excel",
    reportLayout: "تخطيط التقرير",
    standardList: "قائمة عادية",
    roomLayout: "تخطيط الغرف",
    hotelRoomingListQuint: "خماسي",
    
    // Tasks
    addTask: "إضافة مهمة جديدة",
    editTask: "تعديل المهمة",
    taskTitle: "عنوان المهمة",
    relatedBooking: "الحجز المرتبط (اختياري)",
    noRelatedBooking: "لا يوجد حجز مرتبط",
    markAsComplete: "وضع علامة كمكتمل",
    markAsIncomplete: "إزالة علامة الاكتمال",
    overdue: "متأخر",
    noTasksFound: "لم يتم العثور على مهام.",
    noTasksFoundSub: "حاول تعديل الفلاتر أو قم بإنشاء مهمة جديدة.",
    Incomplete: "غير مكتمل",
    // Task Priorities
    High: "عالية",
    Medium: "متوسطة",
    Low: "منخفضة",

    // Activity Log
    user: "المستخدم",
    action: "الإجراء",
    entity: "الكيان",
    details: "التفاصيل",
    timestamp: "الوقت",
    searchActivity: "ابحث بالتفاصيل أو المستخدم...",
    noActivityFound: "لم يتم العثور على نشاط.",
    noActivityFoundSub: "لم يتم تسجيل أي إجراءات بعد.",
    actionType: "نوع الإجراء",
    Created: "إنشاء",
    Updated: "تحديث",
    Deleted: "حذف",
    // Log Messages
    logCreatedCustomer: "أنشأ العميل: {details}",
    logUpdatedCustomer: "حدّث العميل: {details}",
    logDeletedCustomer: "حذف العميل: {details}",
    logCreatedPackage: "أنشأ الباقة: {details}",
    logUpdatedPackage: "حدّث الباقة: {details}",
    logDeletedPackage: "حذف الباقة: {details}",
    logCreatedBooking: "أنشأ الحجز: {details}",
    logUpdatedBooking: "حدّث الحجز: {details}",
    logDeletedBooking: "حذف الحجز: {details}",
    logCreatedPayment: "أضاف دفعة بقيمة {amount} إلى {details}",
    logCreatedExpense: "أضاف مصروف بقيمة {amount} لـ {details}",
    logCreatedTask: "أنشأ المهمة: {details}",
    logUpdatedTask: "حدّث المهمة: {details}",
    logDeletedTask: "حذف المهمة: {details}",
    logCompletedTask: "أكمل المهمة: {details}",
    logIncompleteTask: "ألغى اكتمال المهمة: {details}",
    logCreatedUser: "أنشأ المستخدم: {details}",
    logUpdatedUser: "حدّث المستخدم: {details}",
    logDeletedUser: "حذف المستخدم: {details}",
    logCreatedDocument: "أضاف المستند '{docName}' إلى {details}",
    logDeletedDocument: "حذف المستند '{docName}' من {details}",
    logCreatedExpenseCategory: "أنشأ فئة المصروفات: {details}",
    logUpdatedExpenseCategory: "حدّث فئة المصروفات: {details}",
    logDeletedExpenseCategory: "حذف فئة المصروفات: {details}",

    // Invoice & Receipt
    invoice: "فاتورة",
    flightTicketInvoice: "فاتورة تذكرة طيران",
    invoiceDate: "تاريخ الفاتورة",
    billTo: "إلى العميل",
    itemDescription: "وصف البند",
    subtotal: "المجموع الفرعي",
    amountPaid: "المبلغ المدفوع",
    amountDue: "المبلغ المستحق",
    paymentHistory: "سجل المدفوعات",
    receipt: "إيصال",
    paymentDetails: "تفاصيل الدفعة",
    bookingSummary: "ملخص الحجز",
    totalPackagePrice: "إجمالي سعر الباقة",
    totalPaidToDate: "إجمالي المدفوعات حتى الآن",
    remainingBalance: "الرصيد المتبقي",

    // Confirmations
    confirmDeletionTitle: "تأكيد الحذف",
    confirmDeletionMessage: "لا يمكن التراجع عن هذا الإجراء. هل أنت متأكد من رغبتك في المتابعة؟",
    confirmInvoiceGeneration: "هل أنت متأكد من رغبتك في إنشاء هذه الفاتورة؟",
    confirmReceiptGeneration: "هل أنت متأكد من رغبتك في إنشاء هذا الإيصال؟",
    confirmDeleteCustomer: "هل أنت متأكد من رغبتك في حذف هذا العميل؟ لا يمكن التراجع عن هذا الإجراء.",
    confirmDeletePackage: "هل أنت متأكد من رغبتك في حذف هذه الباقة؟ لا يمكن التراجع عن هذا الإجراء.",
    confirmDeleteBooking: "هل أنت متأكد من رغبتك في حذف هذا الحجز؟ لا يمكن التراجع عن هذا الإجراء.",

    // Toasts
    success: "نجاح",
    error: "خطأ",
    invoiceGeneratedSuccess: "تم إنشاء الفاتورة وتنزيلها.",
    receiptGeneratedSuccess: "تم إنشاء الإيصال وتنزيله بنجاح.",
    bookingSavedSuccess: "تم حفظ الحجز بنجاح.",
    bookingDeletedSuccess: "تم حذف الحجز.",
    customerSavedSuccess: "تم حفظ تفاصيل العميل بنجاح.",
    customerDeletedSuccess: "تم حذف العميل.",
    documentAddedSuccess: "تم رفع المستند بنجاح.",
    documentDeletedSuccess: "تم حذف المستند.",
    packageSavedSuccess: "تم حفظ الباقة بنجاح.",
    packageDeletedSuccess: "تم حذف الباقة.",
    paymentAddedSuccess: "تمت إضافة الدفعة بنجاح.",
    expenseAddedSuccess: "تمت إضافة المصروف بنجاح.",
    taskSavedSuccess: "تم حفظ المهمة بنجاح.",
    taskDeletedSuccess: "تم حذف المهمة.",
    taskStatusChanged: "تم تحديث حالة المهمة.",
    categorySavedSuccess: "تم حفظ الفئة بنجاح.",
    categoryDeletedSuccess: "تم حذف الفئة.",
    fillRequiredFieldsWarning: "يرجى ملء جميع الحقول المطلوبة.",
    genericError: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
    passportExpiryWarning: "يجب أن يكون جواز السفر صالحًا لمدة 6 أشهر على الأقل بعد تاريخ المغادرة.",
    passportSoonToExpireWarning: "يجب أن يكون جواز السفر صالحًا لمدة 6 أشهر على الأقل من تاريخ اليوم.",
    apiKeyNotConfiguredError: "خدمة المسح غير مهيأة. يرجى الاتصال بالدعم.",
    flightDetailsMissingForInvoice: "لا يمكن إنشاء الفاتورة: تفاصيل الرحلة مفقودة لعملية بيع التذكرة هذه.",
    invoicePackageMissingError: "لا يمكن إنشاء الفاتورة: لم يتم العثور على الباقة الخاصة بهذا الحجز (ربما تم حذفها).",
    invoiceCustomerMissingError: "لا يمكن إنشاء الفاتورة: لم يتم العثور على العميل الخاص بهذا الحجز (ربما تم حذفه).",
  }
};